version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - ./database/db:/data/db
  backend:
    image: "clover/backend"
    container_name: backend
    volumes:
      - ./.env:/app/.env
    network_mode: "host"
  frontend:
    image: "clover/frontend"
    container_name: frontend
    volumes:
      - ./.env:/app/.env
    ports:
      - 4012:4012
